package xyroc.morsobscurus;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import net.minecraft.block.Block;
import net.minecraft.item.Item;
import net.minecraft.util.text.TextFormatting;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.Mod.Instance;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.common.registry.GameRegistry;
import xyroc.morsobscurus.block.BlockLooseStoneBrick;
import xyroc.morsobscurus.block.tile.TileEntityEssenceStorage;
import xyroc.morsobscurus.proxy.ServerProxy;
import xyroc.morsobscurus.util.EventManager;
import xyroc.morsobscurus.util.VersionHandler;

@Mod(modid = "morsobscurus", version = "alpha", acceptedMinecraftVersions = "1.12.2")
public class MorsObscurus {

	public static final int versionId = 0;

	@Instance
	MorsObscurus morsObscurus;

	@SidedProxy(serverSide = "xyroc.morsobscurus.proxy.ServerProxy", clientSide = "xyroc.morsobscurus.proxy.ClientProxy")
	public static ServerProxy proxy;

	public static final Logger logger = LogManager.getLogger("Mors Obscurus");

	@EventHandler
	public void preInit(FMLPreInitializationEvent e) {
		logger.info("Pre-initialization");
		ModMetadata data = e.getModMetadata();
		data.autogenerated = false;
		data.name = TextFormatting.RED + "Mors Obscurus";
		data.credits = "XYROC (XIROC)";
		
		MinecraftForge.EVENT_BUS.register(new EventManager());
		proxy.load();
	}

	@EventHandler
	public void init(FMLInitializationEvent e) {
		logger.info("Initialization");
		GameRegistry.registerTileEntity(TileEntityEssenceStorage.class, "morsobscurus:essence_storage");
	}

	@EventHandler
	public void postInit(FMLPostInitializationEvent e) {
		logger.info("Post-initialization");
		VersionHandler.checkForUpdates();
	}
	

}
